// Generated by gencpp from file particle_filter/Particle_vector.msg
// DO NOT EDIT!


#ifndef PARTICLE_FILTER_MESSAGE_PARTICLE_VECTOR_H
#define PARTICLE_FILTER_MESSAGE_PARTICLE_VECTOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <particle_filter/Particle.h>
#include <particle_filter/Pose.h>

namespace particle_filter
{
template <class ContainerAllocator>
struct Particle_vector_
{
  typedef Particle_vector_<ContainerAllocator> Type;

  Particle_vector_()
    : particles()
    , pose_estimate()  {
    }
  Particle_vector_(const ContainerAllocator& _alloc)
    : particles(_alloc)
    , pose_estimate(_alloc)  {
    }



   typedef std::vector< ::particle_filter::Particle_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::particle_filter::Particle_<ContainerAllocator> >::other >  _particles_type;
  _particles_type particles;

   typedef  ::particle_filter::Pose_<ContainerAllocator>  _pose_estimate_type;
  _pose_estimate_type pose_estimate;




  typedef boost::shared_ptr< ::particle_filter::Particle_vector_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::particle_filter::Particle_vector_<ContainerAllocator> const> ConstPtr;

}; // struct Particle_vector_

typedef ::particle_filter::Particle_vector_<std::allocator<void> > Particle_vector;

typedef boost::shared_ptr< ::particle_filter::Particle_vector > Particle_vectorPtr;
typedef boost::shared_ptr< ::particle_filter::Particle_vector const> Particle_vectorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::particle_filter::Particle_vector_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::particle_filter::Particle_vector_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace particle_filter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'particle_filter': ['/home/rudy/Desktop/UMASS/CICS/data/catkin_ws/src/particle_filter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::particle_filter::Particle_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::particle_filter::Particle_vector_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::particle_filter::Particle_vector_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::particle_filter::Particle_vector_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::particle_filter::Particle_vector_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::particle_filter::Particle_vector_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::particle_filter::Particle_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3ac188ff3c52decc5d6ddfaf7ecb36f3";
  }

  static const char* value(const ::particle_filter::Particle_vector_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3ac188ff3c52deccULL;
  static const uint64_t static_value2 = 0x5d6ddfaf7ecb36f3ULL;
};

template<class ContainerAllocator>
struct DataType< ::particle_filter::Particle_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "particle_filter/Particle_vector";
  }

  static const char* value(const ::particle_filter::Particle_vector_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::particle_filter::Particle_vector_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Particle[] particles\n\
Pose pose_estimate\n\
\n\
================================================================================\n\
MSG: particle_filter/Particle\n\
Pose pose\n\
float64 weight\n\
\n\
================================================================================\n\
MSG: particle_filter/Pose\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::particle_filter::Particle_vector_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::particle_filter::Particle_vector_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.particles);
      stream.next(m.pose_estimate);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Particle_vector_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::particle_filter::Particle_vector_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::particle_filter::Particle_vector_<ContainerAllocator>& v)
  {
    s << indent << "particles[]" << std::endl;
    for (size_t i = 0; i < v.particles.size(); ++i)
    {
      s << indent << "  particles[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::particle_filter::Particle_<ContainerAllocator> >::stream(s, indent + "    ", v.particles[i]);
    }
    s << indent << "pose_estimate: ";
    s << std::endl;
    Printer< ::particle_filter::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose_estimate);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARTICLE_FILTER_MESSAGE_PARTICLE_VECTOR_H
