// Generated by gencpp from file particle_filter/Particle.msg
// DO NOT EDIT!


#ifndef PARTICLE_FILTER_MESSAGE_PARTICLE_H
#define PARTICLE_FILTER_MESSAGE_PARTICLE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <particle_filter/Pose.h>

namespace particle_filter
{
template <class ContainerAllocator>
struct Particle_
{
  typedef Particle_<ContainerAllocator> Type;

  Particle_()
    : pose()
    , weight(0.0)  {
    }
  Particle_(const ContainerAllocator& _alloc)
    : pose(_alloc)
    , weight(0.0)  {
    }



   typedef  ::particle_filter::Pose_<ContainerAllocator>  _pose_type;
  _pose_type pose;

   typedef double _weight_type;
  _weight_type weight;




  typedef boost::shared_ptr< ::particle_filter::Particle_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::particle_filter::Particle_<ContainerAllocator> const> ConstPtr;

}; // struct Particle_

typedef ::particle_filter::Particle_<std::allocator<void> > Particle;

typedef boost::shared_ptr< ::particle_filter::Particle > ParticlePtr;
typedef boost::shared_ptr< ::particle_filter::Particle const> ParticleConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::particle_filter::Particle_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::particle_filter::Particle_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace particle_filter

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'particle_filter': ['/home/rudy/Desktop/UMASS/CICS/data/catkin_ws/src/particle_filter/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::particle_filter::Particle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::particle_filter::Particle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::particle_filter::Particle_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::particle_filter::Particle_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::particle_filter::Particle_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::particle_filter::Particle_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::particle_filter::Particle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "17175abc0cf3cd5dc3269c3b10409ae1";
  }

  static const char* value(const ::particle_filter::Particle_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x17175abc0cf3cd5dULL;
  static const uint64_t static_value2 = 0xc3269c3b10409ae1ULL;
};

template<class ContainerAllocator>
struct DataType< ::particle_filter::Particle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "particle_filter/Particle";
  }

  static const char* value(const ::particle_filter::Particle_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::particle_filter::Particle_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Pose pose\n\
float64 weight\n\
\n\
================================================================================\n\
MSG: particle_filter/Pose\n\
float64 x\n\
float64 y\n\
float64 theta\n\
";
  }

  static const char* value(const ::particle_filter::Particle_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::particle_filter::Particle_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
      stream.next(m.weight);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Particle_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::particle_filter::Particle_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::particle_filter::Particle_<ContainerAllocator>& v)
  {
    s << indent << "pose: ";
    s << std::endl;
    Printer< ::particle_filter::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.pose);
    s << indent << "weight: ";
    Printer<double>::stream(s, indent + "  ", v.weight);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PARTICLE_FILTER_MESSAGE_PARTICLE_H
